version: '3.1'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgres://postgreuser:postgrepass@db:5432/wisent"
      DEBUG: "true"
      PORT: 8000
    networks:
      - app
    depends_on:
      - db
  db:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgrepass
      POSTGRES_USER: postgreuser
      POSTGRES_DB: wisent
    volumes:
      - postgredb:/var/lib/postgresql/data
    networks:
      - app

networks:
  app:

volumes:
  postgredb:
